# Generated by Django 6.0.2 on 2026-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('Hen', 'Hen'), ('Cow', 'Cow'), ('Goat', 'Goat')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
